# This file configures automatic builds of Sage on [CircleCI](https://circleci.com).
# To make the build time not too excessive, we seed the build cache with
# sagemath/sagemath-dev:develop. When basic SPKGs change, this does not help much,
# still the full build does usually not exceed CircleCI's limits for open
# source projcets (five hours on 2 vCPUs as of early 2018.)
# You might want to try to build locally or with GitLab CI, see
# `.gitlab-ci.yml` for more options.
# Note that we do not use workflows because it was not clear whether the docker
# images sizes would not exceed the size limits of CircleCI workspaces. Also,
# workflows would not make things faster. We do not get more machines for free
# and the frequent loading of docker images probably exceeds the cost of the
# actual tests.

# As of early 2018, a run on CircleCI takes usually about 25 minutes. Most of
# the time is spent pulling/pushing from/to Docker Hub and copying files
# locally during the docker build. We could probably save five minutes by not
# building and testing the sagemath-dev image for most branches.

version: 2
jobs:
  # As https://circleci.com/docs/2.0/docker-layer-caching/ is a paid feature,
  # we do build & test & release in one step.
  build-check-release:
    machine: true
    # Build for all tags
    tags:
      only: /.*/
    # Build for all branches
    branches:
      only: /.*/
    steps:
    - checkout
    - run:
        command: |
          . .circleci/before-script.sh
          # Build docker images
          .ci/build-docker.sh

          # Test that the images work
          .ci/check-dev.sh $DOCKER_IMAGE_DEV
          .ci/check-cli.sh $DOCKER_IMAGE_CLI
          .ci/check-jupyter.sh $DOCKER_IMAGE_CLI localhost

          # Push docker images to dockerhub if a dockerhub user has been configured
          .ci/push-dockerhub.sh sagemath-dev
          .ci/push-dockerhub.sh sagemath

  doctest-short:
    machine: true
    steps:
    - checkout
    - run:
        command: |
          . .circleci/before-script.sh

          . .ci/pull-dockerhub.sh sagemath

          .ci/test-doctest.sh "$DOCKER_IMAGE" --new
          # TODO: Enable this once we have https://trac.sagemath.org/ticket/25270
          # .ci/test-doctest.sh "$DOCKER_IMAGE" --short

  doctest-long:
    machine: true
    steps:
    - checkout
    - run:
        environment:
          DOCTEST_PARAMETERS: "--long"
        command: |
          . .circleci/before-script.sh

          . .ci/pull-dockerhub.sh sagemath

          .ci/test-doctest.sh "$DOCKER_IMAGE" --long

workflows:
  version: 2
  build-check-release-test:
    jobs:
    - build-check-release
    - doctest-short:
        requires:
        - build-check-release
    - doctest-long-approval:
        type: approval
        requires:
        - doctest-short
    - doctest-long:
        requires:
        - doctest-long-approval
