name: Build & Test using pipenv

on: [push, pull_request]
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv
      run: brew install pipenv
    - name: Install dependencies
      run: brew install pari ppl 
    - name: Create virtual environment
      run: cd src && PIP_USE_PEP517=true pipenv install --dev --skip-lock --sequential --verbose
    - name: Test
      run: cd src && pipenv run python -c 'import sage.all'
 
