name: Build & Test using pipenv

on: [push, pull_request]
  
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv
      run: brew install pipenv
    - name: Install dependencies
      run: brew install pari ppl 
    - name: Create virtual environment
      run: cd src && mkdir -p .venv && pipenv install --dev --skip-lock --sequential && pipenv run pip list
    - name: Install editable manually
      run: cd src && pipenv run pip install -e . --verbose --upgrade --exists-action=i --no-build-isolation
    - name: Test
      run: cd src && pipenv run python -c 'import sage.all'
 
  build-linux:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:20.10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          apt-get install python3-pip
          pip install pipenv
      - name: Install dependencies
        run: apt-get install liblinbox-dev libflint-arb-dev libhomfly-dev libgiac-dev libratpoints-dev libzn-poly-dev libbrial-dev libbrial-groebner-dev libatlas-base-dev libgap-dev
      - name: Create virtual environment
        run: cd src && mkdir -p .venv && pipenv install --dev --skip-lock --sequential && pipenv run pip list
      - name: Install editable manually
        run: cd src && pipenv run pip install -e . --verbose --upgrade --exists-action=i --no-build-isolation
      - name: Test
        run: cd src && pipenv run python -c 'import sage.all'
