name: Build & Test using pipenv

on: [push, pull_request]
  
jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install tools
      run: brew install pipenv tox
    - name: Install dependencies
      run: |
        brew install pari
        tox -e local-homebrew-macos-standard sagelib-build-deps
      env:
        EXTRA_CONFIGURE_ARGS: --enable-build-as-root
        MAKE: make -j6
    - name: Create virtual environment
      run: cd src && mkdir -p .venv && pipenv install --dev --skip-lock && pipenv run pip list
      env:
          PKG_CONFIG_PATH: "/usr/local/opt/openblas/lib/pkgconfig"
    - name: Install editable manually
      run: cd src && pipenv run pip install -e . --verbose --upgrade --exists-action=i --no-build-isolation
      if: always()
      env:
          PKG_CONFIG_PATH: "/usr/local/opt/openblas/lib/pkgconfig"
    - name: Test
      run: cd src && pipenv run python -c 'import sage.all; import sage.doctest.control; sage.doctest.control.run_doctests(sage)'
 
  linux:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:20.10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y tox sudo
          apt-get install -y tzdata keyboard-configuration
          pip install pipenv
          tox -e local-sudo-standard config.status || true
          apt-get remove -y ecl maxima
        env:
          # Needed since otherwise the installation of tzdata/keyboard-configuration hangs
          DEBIAN_FRONTEND: noninteractive
          SKIP_BOOTSTRAP: yes
          SKIP_CONFIGURE: yes
      - name: Build
        run: |
          tox -e local-sudo-standard sagelib-build-deps
          make maxima
        env:
          MAKE: make -j2
          SKIP_SYSTEM_PKG_INSTALL: yes
          # Tox runs everything as root, so we have to enable build as root user
          EXTRA_CONFIGURE_ARGS: "--enable-build-as-root"
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: src/.venv
          key: venv-runner.os-${{ hashFiles('src/Pipfile.lock') }}
      - name: Create virtual environment
        run: |
          cd src 
          mkdir -p .venv
          pipenv install --dev --skip-lock --verbose
          pipenv run pip list
        env:
          PIP_NO_BUILD_ISOLATION: false
      # The following is for testing purposes in case the pipenv install above fails
      - name: Install editable manually
        run: |
          cd src
          pipenv run pip install -e . --verbose --upgrade --exists-action=i --no-build-isolation
        if: always()
      - name: Test
        run: |
          cd src
          pipenv run sage-runtests --all
        env:
          SAGE_LOCAL: ${{GITHUB.WORKSPACE}}/.tox/local-sudo-standard/local
